<link rel="stylesheet" type="text/css" href="/assets/css/general.css">
<link rel="stylesheet" type="text/css" href="/assets/css/dashboard.css">
<link rel="stylesheet" type="text/css" href="/assets/css/filter.css">
<link rel="stylesheet" type="text/css" href="/assets/css/form.css">
<link rel="stylesheet" type="text/css" href="/assets/css/lazy-loading.css">
<link rel="stylesheet" type="text/css" href="/assets/css/module.css">
<link rel="stylesheet" type="text/css" href="/assets/css/navigation.css">
<link rel="stylesheet" type="text/css" href="/assets/css/popup.css">
<link rel="stylesheet" type="text/css" href="/assets/css/table.css">
